<a href="https://colab.research.google.com/github/true-cpu/ThucHanhDeepLearning/blob/main/ThucHanhDeepLearningBuoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

### Các lệnh cơ bản của NumPy

In [ ]:
# Tạo một mảng NumPy
numpy_array = np.array([1, 2, 3, 4, 5])
print("Mảng NumPy:", numpy_array)

# Thực hiện một phép toán cơ bản (ví dụ: nhân với 2)
multiplied_array = numpy_array * 2
print("Mảng sau khi nhân 2:", multiplied_array)

### Các lệnh cơ bản của Pandas

In [2]:
# Tạo một DataFrame từ điển
data = {
    'Tên': ['Alice', 'Bob', 'Charlie', 'David'],
    'Tuổi': [24, 27, 22, 32],
    'Thành phố': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
pd_dataframe = pd.DataFrame(data)

print("DataFrame Pandas:")
display(pd_dataframe)

# Chọn một cột cụ thể
ages = pd_dataframe['Tuổi']
print("\nCột 'Tuổi':")
display(ages)

# Lọc dữ liệu (ví dụ: người có tuổi > 25)
filtered_data = pd_dataframe[pd_dataframe['Tuổi'] > 25]
print("\nDữ liệu được lọc (Tuổi > 25):")
display(filtered_data)

DataFrame Pandas:

       Tên  Tuổi    Thành phố
0    Alice    24     New York
1      Bob    27  Los Angeles
2  Charlie    22      Chicago
3    David    32      Houston

Cột 'Tuổi':

0    24
1    27
2    22
3    32
Name: Tuổi, dtype: int64

Dữ liệu được lọc (Tuổi > 25):

     Tên  Tuổi    Thành phố
1    Bob    27  Los Angeles
3  David    32      Houston